### PR TITLE
deps: support both pydantic 1.0 & 2.0

### PR DESCRIPTION
**Pull request by dsinghvi**

### CODE REVIEW

**Comment by dsinghvi** [comment]
@Vivalldi I think we should put these in a `core/pydantic.py` file and then import pydantic from core

**Comment by Vivalldi** [comment]
I'm realizing I don't fully understand how the repo.

Do I need to add a `core/pydantic.py` for each folder in `seed`? Or is this generated somewhere via `src/fern_python`?

**Comment by dsinghvi** [comment]
> I'm realizing I don't fully understand how the repo works.
> 
> Do I need to add a `core/pydantic.py` for each folder in `seed`? Or is this generated somewhere via `src/fern_python`?

I'll spend some time adding a `Contributing.md`. Seed is basically just a tool that we have that helps us see previews of the generated code.  


The steps would be: 
- Add a core utility for the SDK generator https://github.com/fern-api/fern-python/tree/main/core_utilities/sdk
- Configure to copy the core utility over https://github.com/fern-api/fern-python/blob/4177fafd92e9cde436126e08f85751562520c4c9/src/fern_python/generators/sdk/core_utilities/core_utilities.py#L17-L55
- Update all pydantic imports to import from the core utility instead  https://github.com/fern-api/fern-python/blob/4177fafd92e9cde436126e08f85751562520c4c9/src/fern_python/external_dependencies/pydantic.py#L6-L16

**Comment by dsinghvi** [comment]
closing as handled in a separate PR

**Pull request closed without merging**
