### PR TITLE
Support hiding endpoints from openapi schema

### PR DESCRIPTION
**Pull request by alexrejto**
Closes https://github.com/fern-api/fern-python/issues/301

### CODE REVIEW

**Comment by dsinghvi** [comment]
Looks like mypy is a little mad about typing as `Optional[bool]` vs `bool`

**Comment by dsinghvi** [comment]
@alexrejto if the tests pass then ill merge and create an RC release that you can test with

**Comment by alexrejto** [comment]
sweet!

**Comment by alexrejto** [comment]
@dsinghvi Did you create an rc for this by any chance?

**Comment by dsinghvi** [comment]
just saw that its passing, merging now

**Comment by dsinghvi** [comment]
just tagged `0.3.10-rc0`

**Comment by alexrejto** [comment]
`0.3.10-rc0` works perfectly for me! Do you discourage depending on a release candidate or can I ship this to production while I'm waiting for 0.3.10 ?

**Comment by dsinghvi** [comment]
publishing `0.3.10` now. thanks for the contribution 💪 

we will never change or unpublish RCs so not an issue to depend on them!

**Pull request merged**
